name: lint-and-test
on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install package (editable) + tools
        run: |
          pip install -e .
          pip install -U pip pytest pre-commit

      - name: Run pytest
        run: pytest -q

      - name: Run pre-commit
        run: pre-commit run --all-files
